---
# General simulation parameters
inp_file: wadi_map.inp
network_topology_type: complex
iterations: 500
log_level: info
mininet_cli: false

plcs: !include wadi_plcs.yaml

attacks: !include wadi_attacks.yaml

noise_scale: 0.25

# Initial Conditions
initial_tank_data: initial_tank_wadi.csv
network_loss_data: losses_wadi.csv
network_delay_data: delays_wadi.csv
