---
# General simulation parameters
inp_file: "wadi_map_newer.inp"
network_topology_type: Simple
output_path: "output/"
iterations: 2
mininet_cli: false

plcs: !include wadi_plcs.yaml

attacks: !include wadi_attacks.yaml

batch_simulations: 3
#Initial Conditions
#initial_tank_data: initial_tank_wadi.csv
#demand_patterns: demand_patterns/
#demand_patterns: demand_patterns/2.csv
#network_loss_data: losses_wadi.csv
#network_delay_data: delays_wadi.csv