inp_file: ctown_map.inp
iterations: 2880
network_topology_type: complex
plcs: !include ctown_plcs.yaml
simulator: epynet
demand: pdd
output_path: attack_output_40
demand_patterns: events/demands_ctown_01.csv
initial_tank_data: events/tanks_ctown_01.csv
attacks: !include dataset_attacks/attack_40.yaml
log_level: debug