inp_file: anytown_map.inp
output_path: output
iterations: 10
network_topology_type: complex
plcs: !include anytown_plcs.yaml

simulator: epynet
demand: pdd
log_level: debug
demand_patterns: demands_anytown_small.csv
#attacks: !include anytown_concealment_mitm.yaml