---
# Simulation initialization parameters
initial_custom_flag: "True"
week_index: 0
demand_patterns_path: "../../Demand_patterns/second_batch_three_year_demands_minitown.csv"
starting_demand_path: "../../Demand_patterns/second_batch_random_init_points.csv"
initial_tank_levels_path: "../../Demand_patterns/second_batch_minitown_tank_initial_conditions.csv"

# General simulation parameters
db_path: "minitown_db.sqlite"
db_name: "minitown"
output_ground_truth_path: "physical_process.csv"
duration_days: 7
inp_file: "minitown_map.inp"
simulator: "pdd"
simulation_tpye: "Batch"