---
# Simulation initialization parameters
initial_custom_flag: "True"
week_index: 19
demand_patterns_path: "../../Demand_patterns/three_year_demands_ctown.csv"
starting_demand_path: "../../Demand_patterns/starting_demand_points.csv"
initial_tank_levels_path: "../../Demand_patterns/tank_initial_conditions.csv"

# General simulation parameters
db_path: "ctown_db.sqlite"
output_ground_truth_path: "physical_process.csv"
duration_days: 10
inp_file: "ctown_map.inp"
simulator: "pdd"