inp_file: ctown_map.inp
output_path: /home/robert/ctown_attack1
iterations: 672
network_topology_type: complex
plcs: !include ctown_plcs.yaml
log_level: debug

attacks:
  network_attacks:
  - name: attack1
    type: mitm
    trigger:
      type: below
      sensor: T1
      value: 1.1
    tags:
      - tag: T1
        value: 1.1
    target: PLC2
